# Generated by Django 3.1.1 on 2020-10-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='profiles',
            field=models.ManyToManyField(null=True, related_name='profs', to='admins.Profile'),
        ),
    ]
