# Generated by Django 3.1.1 on 2020-10-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20201002_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='profs', to='admins.Profile'),
        ),
    ]
