# Generated by Django 3.1.1 on 2020-10-04 06:55

import admins.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_noticias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticias',
            new_name='News',
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=admins.models.get_image_filename)),
                ('image_text', models.TextField(max_length=500)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='admins.news')),
            ],
        ),
    ]
