# Generated by Django 3.1.1 on 2020-10-05 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_auto_20201004_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimages',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_images', to='admins.news'),
        ),
    ]
