# Generated by Django 3.1.1 on 2020-11-27 22:23

from django.db import migrations, models
import django.db.models.deletion
import home.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='lucas', max_length=100)),
                ('tipo', models.CharField(choices=[('INICIAL', 'INICIAL'), ('ICONS', 'ICONS'), ('PRODUTO', 'PRODUTO'), ('EMRPESA', 'EMPRESA')], max_length=9)),
                ('text', models.TextField(max_length=500)),
                ('url', models.URLField(null=True)),
                ('front_page', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=home.models.get_image_filename)),
                ('image_text', models.TextField(max_length=500)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='home.banner')),
            ],
        ),
    ]
