# Generated by Django 3.0 on 2020-08-21 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimages',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='home.Banner'),
        ),
    ]
