# Generated by Django 3.0 on 2020-08-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200821_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerimages',
            old_name='url',
            new_name='imagem',
        ),
    ]
