# Generated by Django 3.1.1 on 2020-09-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200822_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='tipo',
            field=models.CharField(choices=[('INICIAL', 'INICIAL'), ('ICONS', 'ICONS')], max_length=9),
        ),
    ]
