# Generated by Django 3.1.1 on 2020-09-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200902_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimages',
            name='image_text',
            field=models.TextField(default='dqwkowqwdkodqwko', max_length=500),
        ),
        migrations.AlterField(
            model_name='banner',
            name='tipo',
            field=models.CharField(choices=[('INICIAL', 'INICIAL'), ('ICONS', 'ICONS'), ('PRODUTO', 'PRODUTO')], max_length=9),
        ),
    ]
