# Generated by Django 3.1.1 on 2020-09-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200902_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimages',
            name='image_text',
            field=models.TextField(max_length=500),
        ),
    ]
